/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package librarymanagementsystem.JFrames;


import librarymanagementsystem.Book;
import librarymanagementsystem.EBook;
import librarymanagementsystem.Library;
import librarymanagementsystem.PrintedBook;

/**
 *
 * @author fadwa
 */
public class MyLibrary extends javax.swing.JFrame {
    Library library;
    /**
     * Creates new form MyLibrary
     */
    public MyLibrary(Library l) {
        initComponents();
        this.library = l; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BookType = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblMenu = new javax.swing.JLabel();
        btnAddBook = new javax.swing.JButton();
        btnDisplayBook = new javax.swing.JButton();
        btnTitle = new javax.swing.JButton();
        btnAuthor = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnRemoveBook = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        addBookPanel = new javax.swing.JPanel();
        lblInfo = new javax.swing.JLabel();
        lblBookTitle = new javax.swing.JLabel();
        lblAuthor = new javax.swing.JLabel();
        lblISBN = new javax.swing.JLabel();
        lblNbPages = new javax.swing.JLabel();
        txtBookTitle = new javax.swing.JTextField();
        btnPrintedBook = new javax.swing.JRadioButton();
        btnEBook = new javax.swing.JRadioButton();
        txtAuthor = new javax.swing.JTextField();
        txtISBN = new javax.swing.JTextField();
        txtNbPages = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        displayBookPanel = new javax.swing.JPanel();
        DisplayBooksPane = new javax.swing.JScrollPane();
        displayBooksField = new javax.swing.JTextArea();
        btnDisplay = new javax.swing.JButton();
        searchByTitlePanel = new javax.swing.JPanel();
        lblEnterTitle = new javax.swing.JLabel();
        txtTitle = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        paneBooks = new javax.swing.JScrollPane();
        txtTab3 = new javax.swing.JTextArea();
        searchByAuthorPanel = new javax.swing.JPanel();
        lblEnterAuthor = new javax.swing.JLabel();
        txtAuthorName = new javax.swing.JTextField();
        btnAuthorSearch = new javax.swing.JButton();
        paneBookTitles = new javax.swing.JScrollPane();
        txtTab4 = new javax.swing.JTextArea();
        removeBookPanel = new javax.swing.JPanel();
        lblSelectBook = new javax.swing.JLabel();
        btnRemove = new javax.swing.JButton();
        txtBooksTitle = new javax.swing.JTextField();
        btnDisplayBooks = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        fieldDisplayBook = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(223, 400));
        setPreferredSize(new java.awt.Dimension(698, 450));
        setResizable(false);
        setSize(new java.awt.Dimension(698, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));

        lblMenu.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblMenu.setForeground(new java.awt.Color(255, 255, 255));
        lblMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagementsystem/JFrames/hellokitty.png"))); // NOI18N
        lblMenu.setText("   Menu");

        btnAddBook.setBackground(new java.awt.Color(255, 255, 255));
        btnAddBook.setForeground(new java.awt.Color(255, 102, 153));
        btnAddBook.setText("Add a Book");
        btnAddBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBookActionPerformed(evt);
            }
        });

        btnDisplayBook.setBackground(new java.awt.Color(255, 255, 255));
        btnDisplayBook.setForeground(new java.awt.Color(255, 102, 153));
        btnDisplayBook.setText("Display All Books");
        btnDisplayBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayBookActionPerformed(evt);
            }
        });

        btnTitle.setBackground(new java.awt.Color(255, 255, 255));
        btnTitle.setForeground(new java.awt.Color(255, 102, 153));
        btnTitle.setText("Search Book By Title");
        btnTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTitleActionPerformed(evt);
            }
        });

        btnAuthor.setBackground(new java.awt.Color(255, 255, 255));
        btnAuthor.setForeground(new java.awt.Color(255, 102, 153));
        btnAuthor.setText("Search Book By Author");
        btnAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAuthorActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(255, 255, 255));
        btnExit.setForeground(new java.awt.Color(255, 102, 153));
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnRemoveBook.setBackground(new java.awt.Color(255, 255, 255));
        btnRemoveBook.setForeground(new java.awt.Color(255, 102, 153));
        btnRemoveBook.setText("Remove Book");
        btnRemoveBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveBookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRemoveBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddBook, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDisplayBook, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAuthor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnAddBook)
                .addGap(32, 32, 32)
                .addComponent(btnDisplayBook)
                .addGap(32, 32, 32)
                .addComponent(btnTitle)
                .addGap(32, 32, 32)
                .addComponent(btnAuthor)
                .addGap(39, 39, 39)
                .addComponent(btnRemoveBook)
                .addGap(37, 37, 37)
                .addComponent(btnExit)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 490));

        addBookPanel.setBackground(new java.awt.Color(255, 204, 204));

        lblInfo.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        lblInfo.setForeground(new java.awt.Color(255, 255, 255));
        lblInfo.setText("Add a new book by entering the details below:");

        lblBookTitle.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        lblBookTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblBookTitle.setText("Book Title:");

        lblAuthor.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        lblAuthor.setForeground(new java.awt.Color(255, 255, 255));
        lblAuthor.setText("Author:");

        lblISBN.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        lblISBN.setForeground(new java.awt.Color(255, 255, 255));
        lblISBN.setText("ISBN:");

        lblNbPages.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        lblNbPages.setForeground(new java.awt.Color(255, 255, 255));
        lblNbPages.setText("Number of pages/filesize:");

        txtBookTitle.setBackground(new java.awt.Color(255, 255, 255));
        txtBookTitle.setForeground(new java.awt.Color(255, 102, 153));
        txtBookTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBookTitleActionPerformed(evt);
            }
        });

        btnPrintedBook.setBackground(new java.awt.Color(255, 204, 204));
        BookType.add(btnPrintedBook);
        btnPrintedBook.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnPrintedBook.setForeground(new java.awt.Color(255, 255, 255));
        btnPrintedBook.setText("Printed Book");

        btnEBook.setBackground(new java.awt.Color(255, 204, 204));
        BookType.add(btnEBook);
        btnEBook.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnEBook.setForeground(new java.awt.Color(255, 255, 255));
        btnEBook.setText("EBook");

        txtAuthor.setBackground(new java.awt.Color(255, 255, 255));
        txtAuthor.setForeground(new java.awt.Color(255, 102, 153));

        txtISBN.setBackground(new java.awt.Color(255, 255, 255));
        txtISBN.setForeground(new java.awt.Color(255, 102, 153));

        txtNbPages.setBackground(new java.awt.Color(255, 255, 255));
        txtNbPages.setForeground(new java.awt.Color(255, 102, 153));

        btnSave.setBackground(new java.awt.Color(255, 255, 255));
        btnSave.setForeground(new java.awt.Color(255, 102, 153));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addBookPanelLayout = new javax.swing.GroupLayout(addBookPanel);
        addBookPanel.setLayout(addBookPanelLayout);
        addBookPanelLayout.setHorizontalGroup(
            addBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addBookPanelLayout.createSequentialGroup()
                .addGroup(addBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addBookPanelLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(addBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(addBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblBookTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblNbPages, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPrintedBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(addBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEBook, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtAuthor, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtISBN, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNbPages, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addBookPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtBookTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(118, 118, 118))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addBookPanelLayout.createSequentialGroup()
                .addGap(0, 53, Short.MAX_VALUE)
                .addGroup(addBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addBookPanelLayout.createSequentialGroup()
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)))
                .addGap(15, 15, 15))
        );
        addBookPanelLayout.setVerticalGroup(
            addBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addBookPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addBookPanelLayout.createSequentialGroup()
                        .addComponent(lblInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(addBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(addBookPanelLayout.createSequentialGroup()
                                .addGroup(addBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblBookTitle)
                                    .addComponent(txtBookTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addGroup(addBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnPrintedBook)
                                    .addComponent(btnEBook))
                                .addGap(36, 36, 36)
                                .addComponent(lblAuthor))
                            .addComponent(txtAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(addBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblISBN))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addComponent(lblNbPages))
                    .addGroup(addBookPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtNbPages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49)
                .addComponent(btnSave)
                .addGap(97, 97, 97))
        );

        jTabbedPane1.addTab("tab1", addBookPanel);

        displayBookPanel.setBackground(new java.awt.Color(255, 204, 204));

        displayBooksField.setBackground(new java.awt.Color(255, 255, 255));
        displayBooksField.setColumns(20);
        displayBooksField.setForeground(new java.awt.Color(255, 102, 153));
        displayBooksField.setRows(5);
        DisplayBooksPane.setViewportView(displayBooksField);

        btnDisplay.setBackground(new java.awt.Color(255, 255, 255));
        btnDisplay.setForeground(new java.awt.Color(255, 102, 153));
        btnDisplay.setText("Display");
        btnDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout displayBookPanelLayout = new javax.swing.GroupLayout(displayBookPanel);
        displayBookPanel.setLayout(displayBookPanelLayout);
        displayBookPanelLayout.setHorizontalGroup(
            displayBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayBookPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(DisplayBooksPane, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, displayBookPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        displayBookPanelLayout.setVerticalGroup(
            displayBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayBookPanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(DisplayBooksPane, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDisplay)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab2", displayBookPanel);

        searchByTitlePanel.setBackground(new java.awt.Color(255, 204, 204));

        lblEnterTitle.setBackground(new java.awt.Color(255, 204, 204));
        lblEnterTitle.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        lblEnterTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblEnterTitle.setText("Enter Book Title:");

        txtTitle.setBackground(new java.awt.Color(255, 255, 255));
        txtTitle.setForeground(new java.awt.Color(255, 102, 153));
        txtTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTitleActionPerformed(evt);
            }
        });

        btnSearch.setBackground(new java.awt.Color(255, 255, 255));
        btnSearch.setForeground(new java.awt.Color(255, 102, 153));
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        txtTab3.setBackground(new java.awt.Color(255, 255, 255));
        txtTab3.setColumns(20);
        txtTab3.setForeground(new java.awt.Color(255, 102, 153));
        txtTab3.setRows(5);
        paneBooks.setViewportView(txtTab3);

        javax.swing.GroupLayout searchByTitlePanelLayout = new javax.swing.GroupLayout(searchByTitlePanel);
        searchByTitlePanel.setLayout(searchByTitlePanelLayout);
        searchByTitlePanelLayout.setHorizontalGroup(
            searchByTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchByTitlePanelLayout.createSequentialGroup()
                .addGroup(searchByTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchByTitlePanelLayout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(lblEnterTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(searchByTitlePanelLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchByTitlePanelLayout.createSequentialGroup()
                .addGap(0, 28, Short.MAX_VALUE)
                .addComponent(paneBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        searchByTitlePanelLayout.setVerticalGroup(
            searchByTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchByTitlePanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblEnterTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchByTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(paneBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab3", searchByTitlePanel);

        searchByAuthorPanel.setBackground(new java.awt.Color(255, 204, 204));

        lblEnterAuthor.setBackground(new java.awt.Color(255, 204, 204));
        lblEnterAuthor.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        lblEnterAuthor.setForeground(new java.awt.Color(255, 255, 255));
        lblEnterAuthor.setText("Enter Author Name:");

        txtAuthorName.setBackground(new java.awt.Color(255, 255, 255));
        txtAuthorName.setForeground(new java.awt.Color(255, 102, 153));
        txtAuthorName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAuthorNameActionPerformed(evt);
            }
        });

        btnAuthorSearch.setBackground(new java.awt.Color(255, 255, 255));
        btnAuthorSearch.setForeground(new java.awt.Color(255, 102, 153));
        btnAuthorSearch.setText("Search");
        btnAuthorSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAuthorSearchActionPerformed(evt);
            }
        });

        txtTab4.setBackground(new java.awt.Color(255, 255, 255));
        txtTab4.setColumns(20);
        txtTab4.setForeground(new java.awt.Color(255, 102, 153));
        txtTab4.setRows(5);
        paneBookTitles.setViewportView(txtTab4);

        javax.swing.GroupLayout searchByAuthorPanelLayout = new javax.swing.GroupLayout(searchByAuthorPanel);
        searchByAuthorPanel.setLayout(searchByAuthorPanelLayout);
        searchByAuthorPanelLayout.setHorizontalGroup(
            searchByAuthorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchByAuthorPanelLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(lblEnterAuthor, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                .addGap(148, 148, 148))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchByAuthorPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(searchByAuthorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchByAuthorPanelLayout.createSequentialGroup()
                        .addComponent(txtAuthorName, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAuthorSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchByAuthorPanelLayout.createSequentialGroup()
                        .addComponent(paneBookTitles, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
        );
        searchByAuthorPanelLayout.setVerticalGroup(
            searchByAuthorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchByAuthorPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblEnterAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchByAuthorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAuthorName, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAuthorSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(paneBookTitles, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab4", searchByAuthorPanel);

        removeBookPanel.setBackground(new java.awt.Color(255, 204, 204));

        lblSelectBook.setBackground(new java.awt.Color(255, 204, 204));
        lblSelectBook.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        lblSelectBook.setForeground(new java.awt.Color(255, 255, 255));
        lblSelectBook.setText("Enter Book Title:");

        btnRemove.setBackground(new java.awt.Color(255, 255, 255));
        btnRemove.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRemove.setForeground(new java.awt.Color(255, 102, 153));
        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        txtBooksTitle.setBackground(new java.awt.Color(255, 255, 255));
        txtBooksTitle.setForeground(new java.awt.Color(255, 102, 153));
        txtBooksTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBooksTitleActionPerformed(evt);
            }
        });

        btnDisplayBooks.setBackground(new java.awt.Color(255, 255, 255));
        btnDisplayBooks.setForeground(new java.awt.Color(255, 102, 153));
        btnDisplayBooks.setText("Display");
        btnDisplayBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayBooksActionPerformed(evt);
            }
        });

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setForeground(new java.awt.Color(255, 102, 153));

        fieldDisplayBook.setBackground(new java.awt.Color(255, 255, 255));
        fieldDisplayBook.setColumns(20);
        fieldDisplayBook.setForeground(new java.awt.Color(255, 102, 153));
        fieldDisplayBook.setRows(5);
        jScrollPane2.setViewportView(fieldDisplayBook);

        javax.swing.GroupLayout removeBookPanelLayout = new javax.swing.GroupLayout(removeBookPanel);
        removeBookPanel.setLayout(removeBookPanelLayout);
        removeBookPanelLayout.setHorizontalGroup(
            removeBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removeBookPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(removeBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(removeBookPanelLayout.createSequentialGroup()
                        .addComponent(lblSelectBook)
                        .addGap(36, 36, 36)
                        .addComponent(txtBooksTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(78, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, removeBookPanelLayout.createSequentialGroup()
                        .addGroup(removeBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(removeBookPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(removeBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnDisplayBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(20, 20, 20))))
        );
        removeBookPanelLayout.setVerticalGroup(
            removeBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removeBookPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(removeBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSelectBook, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBooksTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDisplayBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab5", removeBookPanel);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, -40, -1, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBookActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_btnAddBookActionPerformed

    private void btnDisplayBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayBookActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_btnDisplayBookActionPerformed

    private void btnTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTitleActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_btnTitleActionPerformed

    private void btnAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAuthorActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_btnAuthorActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnRemoveBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveBookActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(4);
    }//GEN-LAST:event_btnRemoveBookActionPerformed

    private void txtAuthorNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAuthorNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAuthorNameActionPerformed

    private void txtBookTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBookTitleActionPerformed
        // TODO add your handling code here:
            
    }//GEN-LAST:event_txtBookTitleActionPerformed

    private void btnDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayActionPerformed
        // TODO add your handling code here:
        String t = library.retrieveAllBooks();
        displayBooksField.setText(t);
    }//GEN-LAST:event_btnDisplayActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        int p = Integer.parseInt(txtNbPages.getText());
        double fs = Double.parseDouble(txtNbPages.getText());
        if(btnPrintedBook.isSelected()){
            PrintedBook pb = new PrintedBook();
            pb.setTitle(txtBookTitle.getText());
            pb.setAuthor(txtAuthor.getText());
            pb.setIsbn(txtISBN.getText());
            pb.setPages(p);
            library.addBook(pb);
        }else if(btnEBook.isSelected()){
            EBook eb = new EBook();
            eb.setTitle(txtBookTitle.getText());
            eb.setAuthor(txtAuthor.getText());
            eb.setIsbn(txtISBN.getText());
            eb.setFilesize(fs);
            library.addBook(eb);
        }
        txtAuthor.setText("");
        txtBookTitle.setText("");
        txtISBN.setText("");
        txtNbPages.setText("");
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String i = library.retrieveBookByTitle(txtTitle.getText());
        txtTab3.setText(i);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnAuthorSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAuthorSearchActionPerformed
        // TODO add your handling code here:
        String a = library.retrieveBookByAuthor(txtAuthorName.getText());
        txtTab4.setText(a);
    }//GEN-LAST:event_btnAuthorSearchActionPerformed

    private void txtBooksTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBooksTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBooksTitleActionPerformed

    private void btnDisplayBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayBooksActionPerformed
        // TODO add your handling code here:
        String r = library.retrieveAllBooks();
        fieldDisplayBook.setText(r);
    }//GEN-LAST:event_btnDisplayBooksActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        Book book = library.findBookByTitle(txtBooksTitle.getText());
        library.removeBook(book);
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void txtTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTitleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BookType;
    private javax.swing.JScrollPane DisplayBooksPane;
    private javax.swing.JPanel addBookPanel;
    private javax.swing.JButton btnAddBook;
    private javax.swing.JButton btnAuthor;
    private javax.swing.JButton btnAuthorSearch;
    private javax.swing.JButton btnDisplay;
    private javax.swing.JButton btnDisplayBook;
    private javax.swing.JButton btnDisplayBooks;
    private javax.swing.JRadioButton btnEBook;
    private javax.swing.JButton btnExit;
    private javax.swing.JRadioButton btnPrintedBook;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnRemoveBook;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnTitle;
    private javax.swing.JPanel displayBookPanel;
    private javax.swing.JTextArea displayBooksField;
    private javax.swing.JTextArea fieldDisplayBook;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblAuthor;
    private javax.swing.JLabel lblBookTitle;
    private javax.swing.JLabel lblEnterAuthor;
    private javax.swing.JLabel lblEnterTitle;
    private javax.swing.JLabel lblISBN;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JLabel lblNbPages;
    private javax.swing.JLabel lblSelectBook;
    private javax.swing.JScrollPane paneBookTitles;
    private javax.swing.JScrollPane paneBooks;
    private javax.swing.JPanel removeBookPanel;
    private javax.swing.JPanel searchByAuthorPanel;
    private javax.swing.JPanel searchByTitlePanel;
    private javax.swing.JTextField txtAuthor;
    private javax.swing.JTextField txtAuthorName;
    private javax.swing.JTextField txtBookTitle;
    private javax.swing.JTextField txtBooksTitle;
    private javax.swing.JTextField txtISBN;
    private javax.swing.JTextField txtNbPages;
    private javax.swing.JTextArea txtTab3;
    private javax.swing.JTextArea txtTab4;
    private javax.swing.JTextField txtTitle;
    // End of variables declaration//GEN-END:variables
}
